# Generated by Django 5.2.4 on 2025-07-11 13:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.PositiveBigIntegerField()),
                ('duration', models.DurationField(help_text='Estimated repair duration')),
                ('part_quality', models.CharField(choices=[('OEM', 'OEM'), ('3RDPARTY', '3RD_PARTY')], default='OEM', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'PENDING'), ('A', 'ACCEPTED'), ('R', 'REJECTED'), ('E', 'EXPIRED')], default='P', max_length=1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='job.repairjob')),
                ('repairer', models.ForeignKey(limit_choices_to={'repairer': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
