# Generated by Django 5.2.4 on 2025-07-12 16:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_bid_message_bid_warranty_alter_bid_id_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='bid',
        #     name='id',
        #     field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        # ),
    ]
